version: '3.3'

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        DOCKER_ROOT: ${DOCKER_ROOT}
        DJANGO_ROOT: ${DJANGO_ROOT}
    image: django-app
    container_name: django-app_web
    restart: always
    volumes:
      - ${DJANGO_ROOT}:/code
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - NTUB_AUTH_API_DOMAIN=${NTUB_AUTH_API_DOMAIN}
      - NTUB_AUTH_API_URL=${NTUB_AUTH_API_URL}
      - DATABASE_URL=${DATABASE_URL}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    depends_on:
      - db

  caddy:
    image: caddy:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${DOCKER_ROOT}/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app

volumes:
  caddy_data:
  caddy_config:
