# Generated by Django 3.1.2 on 2020-10-17 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200822_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventattachment',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='events.event'),
        ),
    ]
