# Generated by Django 3.1.2 on 2020-10-17 09:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0003_auto_20201017_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(related_name='participants', through='events.EventParticipant', to=settings.AUTH_USER_MODEL),
        ),
    ]
