# Generated by Django 3.1.2 on 2020-10-25 07:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0004_auto_20201017_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventparticipant',
            name='reply',
            field=models.CharField(choices=[('accept', '接受'), ('decline', '拒絕'), ('maybe', '不確定'), ('no_reply', '未回應')], default='no_reply', max_length=15, verbose_name='回應'),
        ),
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(related_name='participate_events', through='events.EventParticipant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscribe_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
