# Generated by Django 3.1.2 on 2020-10-20 06:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0004_auto_20201017_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(related_name='participate_events', through='events.EventParticipant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscribe_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
