version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        DOCKER_ROOT: ${DOCKER_ROOT}
        DJANGO_ROOT: ${DJANGO_ROOT}
    image: django-app
    container_name: django-app_web
    restart: always
    volumes:
      - ${DJANGO_ROOT}:/code
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - NTUB_AUTH_API_DOMAIN=${NTUB_AUTH_API_DOMAIN}
      - NTUB_AUTH_API_URL=${NTUB_AUTH_API_URL}
      - DATABASE_URL=${DATABASE_URL}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    ports:
      - "8000:8000"
  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - ${DJANGO_ROOT}/media/:/var/www/media/
      - ${DJANGO_ROOT}/assets/:/var/www/assets/:ro
      - ${DOCKER_ROOT}/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - app
