# Generated by Django 3.0.8 on 2020-08-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_commonmeeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('teacher', '老師'), ('student', '學生'), ('unknow', '不知名'), ('system', '系統管理者')], default='unknow', max_length=15),
        ),
    ]
