# Generated by Django 3.0.6 on 2020-05-08 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calendars', '0001_initial'),
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permission',
            name='calendar_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendars.Calendar'),
        ),
        migrations.AddField(
            model_name='permission',
            name='group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('user_id', 'calendar_id')},
        ),
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together={('group_id', 'calendar_id')},
        ),
    ]
