# Generated by Django 3.0.6 on 2020-05-08 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calendars', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='events.Attachment'),
        ),
        migrations.AddField(
            model_name='event',
            name='calendars',
            field=models.ManyToManyField(to='calendars.Calendar'),
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('user_id', 'event_id')},
        ),
    ]
