# Generated by Django 3.0.6 on 2020-05-15 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calendars', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='calendars',
            field=models.ManyToManyField(to='calendars.Calendar'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='events.Event'),
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('user', 'event')},
        ),
    ]
