# Generated by Django 3.0.6 on 2020-05-12 11:42

import app.events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200512_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='name',
            field=models.FileField(upload_to=app.events.models.Attachment.attachment_path),
        ),
    ]
