# Generated by Django 3.0.6 on 2020-05-16 09:27

import app.events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200516_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to=app.events.models.Attachment.attachment_path, verbose_name='檔案位置'),
        ),
        migrations.AlterField(
            model_name='event',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立時間'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='備註'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_at',
            field=models.DateTimeField(verbose_name='結束時間'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.TextField(blank=True, null=True, verbose_name='地點'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_at',
            field=models.DateTimeField(verbose_name='開始時間'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=50, verbose_name='行程名稱'),
        ),
        migrations.AlterField(
            model_name='event',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新時間'),
        ),
    ]
