# Generated by Django 3.0.6 on 2020-05-12 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20200512_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='events.Event'),
        ),
    ]
