# Generated by Django 3.1.3 on 2020-11-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegrambot',
            name='emails',
        ),
        migrations.AlterField(
            model_name='telegrambot',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
