# Generated by Django 3.0.6 on 2020-05-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0002_auto_20200516_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='role',
            field=models.CharField(choices=[('r', '可讀'), ('w', '可寫')], max_length=10),
        ),
    ]
