# Generated by Django 3.1 on 2020-09-05 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0002_auto_20200822_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendar',
            old_name='permission',
            new_name='groups',
        ),
        migrations.AlterField(
            model_name='calendarpermission',
            name='calendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='calendars.calendar'),
        ),
    ]
