# Generated by Django 3.1.1 on 2020-09-12 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('calendars', '0003_auto_20200905_1735'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='calendarpermission',
            unique_together={('group', 'calendar', 'role')},
        ),
    ]
