# Generated by Django 3.0.8 on 2020-07-30 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0004_calendar_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='display',
            field=models.CharField(choices=[('public', '公開'), ('private', '不公開')], max_length=10),
        ),
    ]
