# Generated by Django 3.1.2 on 2020-10-14 11:25

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0004_auto_20200912_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
    ]
