# Generated by Django 3.0.8 on 2020-07-31 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0006_auto_20200730_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='authority',
            field=models.CharField(choices=[('r', '可讀'), ('w', '可寫')], default='r', max_length=10),
        ),
        migrations.AlterField(
            model_name='permission',
            name='role',
            field=models.CharField(choices=[('teacher', '老師'), ('student', '學生'), ('unknow', '不知名'), ('system', '系統管理者')], default='system', max_length=15),
        ),
    ]
